name: Test
on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Setup Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.18'

      - name: Bootstrap tools
        run: make bootstrap-tools

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test
