name: Test
on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '1.18'

      - name: Bootstrap tools
        run: make bootstrap-tools

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test
